apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testchartargo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Shreyas2792/argohelm.git
    targetRevision: HEAD
    path: testchartargo
  destination: 
    server: https://kubernetes.default.svc
    namespace: mytestargoapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
